### ISSUE TITLE
Documentation on how to use the library

### ISSUE THREAD

**Issue by EskelinenAntti** [ruuvi/com.ruuvi.bluetooth.default#11]
Hi,

I'm trying to read data from Ruuvi tags in my custom Android application and thought it might be possible with this com.ruuvi.bluetooth.default library. However, there is no documentation about how to use the library. Could you provide some simple "Getting started" steps for example in the [README.md](https://github.com/ruuvi/com.ruuvi.bluetooth.default/blob/master/README.md)? Short code snippets on how to initialize the library, how to search tags and how to read data from found tags would be very helpful.

Regards,
Antti Eskelinen

**Comment by ojousima** [comment]
Hello, 

I'm assigning to @io53 as he's been the last person to work with the library. I can't promise any schedules yet, let's take a look at that separately @io53

**Comment by io53** [comment]
Great idea. The readme is not very helpful so its about time do so something about it :).
