### ISSUE TITLE
Disconnected when reading history via BLE GATT

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.bluetooth.default#31]
Phone: Samsung Galaxy S21 Ultra

After some time since full phone reboot, RuuviTag history GATT sync becomes totally unusable. It either manages to read 10-100 datapoints or none before Disconnected message is shown. I have reproduced this several times. Toggling Bluetooth off and on and killing the app has no effect. Only phone reboot helps.

Videos:

https://user-images.githubusercontent.com/1311912/133599450-f11279d2-3f00-42de-8608-dfff42a0ebb8.mp4

https://user-images.githubusercontent.com/1311912/133599425-25ee9f29-a190-4a49-a070-b1e9fcefa19b.mp4

**Comment by laurijamsa** [comment]
More videos:

https://user-images.githubusercontent.com/1311912/133878469-ace6ddbf-e422-4887-a45e-3fb137d0a285.mp4

https://user-images.githubusercontent.com/1311912/133878475-28a0e42c-a11e-4e25-b378-03b0f39ccddc.mp4

https://user-images.githubusercontent.com/1311912/133878476-981bc0a2-caa2-476c-ac4a-ad510b5912e3.mp4

**Comment by laurijamsa** [comment]
Videos right after a full phone reboot:

https://user-images.githubusercontent.com/1311912/133878936-7de3a0be-d837-4626-b308-9f52813f1cdc.mp4

https://user-images.githubusercontent.com/1311912/133878941-27f5d194-687d-40bd-88b2-083d9e8976eb.mp4

https://user-images.githubusercontent.com/1311912/133878945-2170e356-6c1c-44b8-ab55-78384f875ebf.mp4

**Comment by markoaamunkajo** [comment]
This has improved for me considerably, moving to done.
